stages:
  - build

build and test linux:
  stage: build
  image:
    name: registry.gitlab.com/ultimaker/cura/cura-build-environment:centos7-WIP_win_docker-54
  tags:
    - cura
    - docker
    - linux
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build
